### ISSUE TITLE
API is down (due to the API hosting service)

### ISSUE THREAD

**Issue by aamir-asaram** [beyarkay/eskom-calendar-api#3]
Hey, I've been using this API for a small personal project I've been working on for the past few days but it doesn't seem to be working anymore? 
![image](https://github.com/beyarkay/eskom-calendar-api/assets/76215321/f36dc2c1-ae6d-4839-8497-0b16442420f3)

**Comment by beyarkay** [comment]
Thanks for letting me know. It looks like the service I'm using to host the API is having some issues. Busy chatting with their team now to get an ETA for a fix. Unfortunately there's not much I can do until then. I'll keep this issue updated as things progress.
