### ISSUE TITLE
API Access Issue: Is the Service Down?

### ISSUE THREAD

**Issue by Mikeygoldman1** [beyarkay/eskom-calendar-api#6]
Hi,

I've been unable to access the API. Before I troubleshoot further, could you please confirm if the service is operational?

Thank you

![image](https://github.com/beyarkay/eskom-calendar-api/assets/88478063/99c5f8d6-ee53-48af-b18f-9bc98b4e5561)

**Comment by beyarkay** [comment]
Hi there, 

Apologies, I'm having some trouble with keeping the servers up and running. They should be back up now.
